apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-akhikachmoney
  labels:
    app: web-akhikachmoney
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-akhikachmoney
  template:
    metadata:
      labels:
        name: web-akhikachmoney
    spec:
      containers:
        - name: web-akhikachmoney
          image: akhibousokhona1/akhikachmoney:v1.2
          imagePullPolicy: Always
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 64Mi
              cpu: 100m
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: django-postgres-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-postgres-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: django-postgres-credentials
                  key: userdb
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: django-postgres-credentials
                  key: dbhost
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: django-postgres-credentials
                  key: port
