apiVersion: v1
kind: Service
metadata:
   name: web-akhikachoney
spec:
   selector:
      app: web-akhikachoney
   type: LoadBalancer
   ports:
   -  name: http
      port: 80
      targetPort: 8000
      protocol: TCP


apiVersion: v1
kind: Service
metadata:
  name: web-akhikachoney
  labels:
    app: web-akhikachoney
spec:
  type: LoadBalancer
  ports:
    - port: 80 #port that the service exposes
      targetPort: 8000 #port that the app is receiving requests from via the pod
  selector:
    name: web-akhikachoney
